'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EliminarFacturas

  '''<summary>
  '''Panel1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''Titulo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Titulo As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''NFactura control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents NFactura As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''TBNFactura control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TBNFactura As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''LblEliminarFactura control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblEliminarFactura As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''Eliminar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Eliminar As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''Retornar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Retornar As Global.System.Web.UI.WebControls.Button
End Class
