'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegistroFacturas

  '''<summary>
  '''Panel1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''TBFecha control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TBFecha As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''LblFecha control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblFecha As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''TBNFactura control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TBNFactura As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''LblFactura control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblFactura As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''Label2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''TBNombreCliente control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TBNombreCliente As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''LblCliente control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblCliente As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''TBNIT control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TBNIT As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''LblNIT control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblNIT As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LbProducto control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LbProducto As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''DLPRODUCTO control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents DLPRODUCTO As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''PRODUCTO control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents PRODUCTO As Global.System.Web.UI.WebControls.SqlDataSource

  '''<summary>
  '''LblCarntidad control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblCarntidad As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''TBCantidad control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TBCantidad As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''Agregar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Agregar As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''GridProductos control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents GridProductos As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''Guardar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Guardar As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''Anular control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Anular As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''Eliminar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Eliminar As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''Buscar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Buscar As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''Limpiar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Limpiar As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''LblResultado control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblResultado As Global.System.Web.UI.WebControls.Label
End Class
